/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#341100",
        "surface-container-high": "#ece7e7",
        "primary-container": "#265478",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "outline-variant": "#c2c7cf",
        "surface-container": "#f1edec",
        "on-secondary-fixed-variant": "#793100",
        "background": "#fdf8f8",
        "outline": "#72787f",
        "tertiary-container": "#525050",
        "surface": "#fdf8f8",
        "secondary-container": "#fb6d00",
        "on-primary-container": "#9dc8f1",
        "tertiary": "#3b3939",
        "on-surface": "#1c1b1b",
        "on-secondary-container": "#562100",
        "on-primary-fixed": "#001d32",
        "primary": "#033d60",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#1a4a6e",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#c6c2c2",
        "tertiary-fixed-dim": "#c9c5c5",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffdbcb",
        "on-surface-variant": "#42474e",
        "surface-dim": "#ddd9d9",
        "surface-container-highest": "#e6e1e1",
        "on-tertiary-fixed-variant": "#484646",
        "on-background": "#1c1b1b",
        "primary-fixed-dim": "#a0cbf5",
        "on-secondary": "#ffffff",
        "surface-variant": "#e6e1e1",
        "inverse-on-surface": "#f4f0ef",
        "secondary-fixed-dim": "#ffb691",
        "inverse-primary": "#a0cbf5",
        "surface-tint": "#366287",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#e6e1e1",
        "on-tertiary-fixed": "#1c1b1b",
        "on-error-container": "#93000a",
        "surface-container-low": "#f7f2f2",
        "primary-fixed": "#cde5ff",
        "secondary": "#9e4200",
        "inverse-surface": "#313030",
        "surface-bright": "#fdf8f8"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"],
        "plus-jakarta-sans": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
